### ISSUE TITLE
plls fails when no coords are named channels

### ISSUE THREAD

**Issue by ianhi** [Hekstra-Lab/microutil#9]
I would expect this code to run:

```python
import microutil as mu
import numpy as np
import xarray as xr

mu.squash_zstack(
    xr.DataArray(
        np.random.randint(0, 255, size=(5, 512, 512)),
        dims=("z", "x", "y"),
    )
)
```

In the case of `channels` missing from dims then maybe squash_zstack should just assume it's been passed a BF stack. Or at the very least it should raise an error saying that this is not allowed

**Comment by jrussell25** [comment]
So of course its not documented but it depends on having `x`, `y` (and eventually `z` for final selections) as dims. It would be easy enough to default to using the last two dims for the PLLS part but  im not sure how to elegantly handle selecting or squashing along an unnamed `z` dimension.

**Comment by ianhi** [comment]
Sorry, I don't mean about `z` I mean that if you have `arr` with dims: `('t', 'channel', 'z', 'y', 'x')`
then `mu.squash_zstack(BF.sel(channel='BF'))` will fail. Which is admittedly a weird example, but it's a shame that squashing won't work for a time series that lacks an flours. e.g. if you only did BF and raman
